module.exports =  {
  appMake:  {
    appName: 'btw',
    appDescription: 'I am using distro btw.',
    type: 'chatInput',
    permissions: []
  },
  name: 'btw',
  module: 'api',
  async execute(msg)  {
    let distroSel = [
      "MX Linux","Manjaro Linux","Linux Mint","Ubuntu","Debian","elementary OS",
      "Solus","Zorin OS","Fedora","deepin","KDE neon","Pop!_OS","antiX",
      "Arch Linux","CentOS","ArcoLinux","openSUSE","PCLinuxOS","Ubuntu Kylin","Kali Linux",
      "EndeavourOS","Linux Lite","Puppy Linux","Peppermint OS","EasyOS","SparkyLinux","Lubuntu",
      "FreeBSD","Tails","ReactOS","Q4OS","Xubuntu","Android-x86","Kubuntu",
      "Slackware Linux","Archman GNU/Linux","Alpine Linux","Devuan GNU+Linux","Parrot","Ubuntu MATE","Void",
      "Endless OS","Mageia","Feren OS","Bodhi Linux","GhostBSD","Gentoo Linux","Bluestar Linux",
      "PureOS","Simplicity Linux","OpenMandriva Lx","Project Trident","KaOS","Red Hat Enterprise Linux","4MLinux",
      "ClearOS","Clear Linux","CyberOS","ExTiX","Tiny Core Linux","Nitrux","Ubuntu Budgie",
      "KNOPPIX","NixOS","AV Linux","LXLE","Qubes OS","BlackArch Linux","Elive",
      "Netrunner","Voyager Live","NomadBSD","Robolinux","Emmabuntüs","Ultimate Edition","Linux Kodachi",
      "SmartOS","Ubuntu Studio","DragonFly BSD","ALT Linux","OpenBSD","Volumio","Linuxfx",
      "Artix Linux","FuryBSD","AUSTRUMI","AryaLinux","Septor","MakuluLinux","SteamOS",
      "Trisquel GNU/Linux","BunsenLabs Linux","Lakka","Raspbian","Obarun","Absolute Linux","ArchBang Linux",
      "Sabayon","Haiku","ROSA","ArchLabs Linux","Archcraft","BackBox Linux","LibreELEC",
      "GoboLinux","Slax","Clonezilla Live","Oracle Linux","NuTyX","NetBSD","Whonix",
      "Calculate Linux","Anarchy Installer","SystemRescueCd","IPFire","OpenMediaVault","LinuxConsole","Redcore Linux",
      "UBports","BEE free","SuperGamer","Exe GNU/Linux","OpenIndiana","Parabola GNU/Linux-libre","Porteus",
      "SliTaz GNU/Linux","FreeNAS","SUSE Linux Enterprise","DuZeru","Rescatux","Runtu","AcademiX GNU/Linux",
      "Guix System","Hyperbola GNU/Linux-libre","Parted Magic","Zenwalk Linux","Container Linux","GParted Live","Raspberry Slideshow",
      "Linux From Scratch","Minimal Linux Live","Bicom Systems","EasyNAS","Debian Edu/Skolelinux","Peach OSI","KolibriOS",
      "OLPC OS","RebeccaBlackOS","pfSense","SolydXK","TurnKey Linux","Ufficio Zero","KANOTIX",
      "OPNsense","Oracle Solaris","OSMC","Pardus","Community","Porteus Kiosk","Trusted End Node Security",
      "Live Raizo","Untangle NG Firewall","Ubuntu DesktopPack","Zentyal Server","Berry Linux","Freespire","Funtoo Linux",
      "Greenie Linux","Zevenet","APODIO","Fatdog64 Linux","GALPon MiniNo","Star","GeckoLinux",
      "Proxmox","Finnix","Raspberry Digital Signage","RancherOS","Univention Corporate Server","3CX Phone System","Neptune",
      "Pinguy OS","ArchStrike","Karoshi","MidnightBSD","Exherbo","Plamo Linux","CAINE",
      "CRUX","XigmaNAS","Wifislax","Bedrock Linux","Pearl Linux OS","Refracta","batocera.linux",
      "blackPanther OS","Lunar Linux","Namib GNU/Linux","Pisi Linux","BigLinux","CAELinux","Slackel",
      "ClonOS","DRBL Live","Dragora GNU/Linux-Libre","Grml","DietPi","Enso OS","HardenedBSD",
      "EuroLinux","FuguIta","Linspire","Network Security Toolkit","SuperX","VyOS","Daphile",
      "RISC OS Open","CloudReady","MorpheusArch Linux","NethServer","Pentoo","Vine Linux","BOSS GNU/Linux",
      "Secure-K OS","Stella","UBOS","Zeroshell","Asianux","Cucumber Linux","LliureX",
      "Sophos UTM","Source Mage GNU/Linux","T2 SDE","BSD Router Project","FreedomBox","Photon OS","Plop Linux",
      "SharkLinux","Super Grub2 Disk","Thinstation","BlueOnyx","Elastix","ForLEx","Rocks Cluster Distribution",
      "openmamba GNU/Linux","Endian Firewall","Springdale Linux","Hanthana Linux","LinHES","paldo GNU/Linux","Clu Linux Live",
      "Hamara","LuninuX OS","NexentaStor","PLD Linux Distribution","PrimTux","Smoothwall Express","ToOpPy Linux",
      "Baruwa Enterprise Edition","Kwort Linux","Omarine","Openwall GNU/*/Linux","OviOS Linux","SELKS","Securepoint Security Suite",
      "YunoHost","FreePBX","OB2D Linux","OSGeoLive","ARMA aka Omoikane GNU/Linux","Pardus Topluluk","Corporate",
      "Recalbox","SME Server","Webconverger","tuxtrans","Swift Linux","KISS","Uruk GNU/Linux",
      "Redo Backup &amp; Recovery","0Linux","2XOS","64 Studio","AbulÉdu","Adamantix","ADIOS Linux Boot CD",
      "AgiliaLinux","All in One - System Rescue Toolkit","Aleader","Alinex","aLinux","AliXe","Amarok Live",
      "Amber Linux","Ankur Bangla","Annvix","AnNyung Linux","Anonym.OS LiveCD","ANTEMIUM Linux","Antergos",
      "Antomic GNU/Linux","Apricity OS","aptosid","Arabbix","Arabian Linux","ArcheOS","Archie Live CD",
      "Ares Desktop","AriOS","Ark Linux","arkOS","ArtistX","Arudius","AsianLinux",
      "ASLinux","ASPLinux","Asturix","Athene Operating System","ATmission","Atomix","Audiophile Linux",
      "Augustux","Aurora SPARC Linux","Aurora OS","Aurox Linux","Hubworx","BackSlash Linux","Baltix GNU/Linux",
      "Bardinux","Bayanihan Linux","BeaFanatIX","BeakOS","BearOps Desktop Linux OS","BeatrIX Linux","Bee Linux",
      "Beehive Linux","BEERnix","BeleniX","Bella OS","Biadix","BinToo GNU/Linux","BioBrew Linux Distribution",
      "Bioknoppix","Bio-Linux","BitKey","Black Lab Linux","BlackRhino GNU/Linux","BLAG Linux And GNU","BlankOn",
      "Blin Linux","Blue Linux","BluePoint Linux","Bluewall GNU/Linux","Bluewhite Linux","Bonzai Linux","Boten GNU/Linux",
      "Bridge Linux","BRLix","BrlSpeak","BSDanywhere","Buffalo Linux","Boston University Linux","Burapha Linux Server",
      "Build Your Own (BYO) Linux","ByzantineOS","Linux Caixa Mágica","Canaima GNU/Linux","Caos Linux","Càtix","CCux Linux",
      "CDlinux","CensorNet","Centrych OS","Chakra GNU/Linux","ChaletOS","Chapeau","Chinese 2000 Linux",
      "Chitwanix OS","Chinese Linux Extension","Clusterix","clusterKNOPPIX","Cobind Desktop","College Linux","Comfusion",
      "Commodore OS Vision","Condorux","Condres OS","Conectiva Linux","ConnochaetOS","Cool Linux CD","Core GNU/Linux",
      "Corel Linux","Coyote Linux","CPUBuilders Linux","CrunchBang Linux","CTKArch","Cub Linux","Damn Small Linux",
      "DANIX GNU/Linux","DARKSTAR Linux","Debris Linux","DebXPde","Deep-Water/Linux","LinuxDefender Live! CD","DEFT Linux",
      "Definity Linux","DemoLinux","AGNULA GNU/Linux Audio Distribution","Descent|OS","DesktopBSD","Devil-Linux","DigAnTel",
      "Discreete Linux","Dizinha Linux","DNALinux","DoudouLinux","Draco GNU/Linux","Dreamlinux","DreamStudio",
      "P!tux Linux","Damn Vulnerable Linux","Dynasoft Linux","dyne:bolic","Dzongkha Linux","Eadem Enterprise AS","Eagle Linux",
      "eAR OS","EasyPeasy","easys GNU/Linux","Edubuntu","eduKnoppix","EduLinux","Ehad",
      "Ekaaty Linux","eLearnix","Element","elpicx","ELX Linux","EnGarde Secure Linux","Epidemic GNU/Linux",
      "Eridani Linux","ERPOSS","Estrella Roja","ESUN Linux","ESware LinuX","Euronode","EvilEntity Linux",
      "Evinux","eZeY","EzPlanet One Linux","FaunOS","Feather Linux","Featherweight Linux","Fermi Linux",
      "F.I.R.E.","Firefly Linux","Flash Linux","Flonix","Fluxbuntu Linux","Foresight Linux","Vital Data Forensic or Rescue Kit (FoRK)",
      "FoX Desktop","Freedows","Freeduc-cd","Freeduc-Sup","Freepia","FreeSBIE - FreeBSD Live CD","Frenzy",
      "Frugalware Linux","FTOSX Desktop","Fuduntu","Fusion Linux","Garuda Linux","GeeXboX","Gelecek Linux",
      "GenieOS","GentooTH Live CD/USB Linux","Gentoox","GEOLivre Linux","Gibraltar Firewall","Ging","GnackTrack",
      "gNewSense","GNIX-Vivo","GNOBSD","Gnoppix Linux","gNOX","GNUstep Live CD","gOS",
      "Grafpup Linux","Granular Linux","Guadalinex","GuLIC-BSD","h3knix","Haansoft Linux","Hacao Linux",
      "Hakin9 Live","Hancom Linux","HandyLinux","Happy Linux","Happy MacLinux","Haydar Linux","heads","Hedinux GNU/Linux",
      "Helix","Heretix","Hikarunix","HispaFuentes Linux","HKLPG Linux","Holon Linux","Honeywall CDROM",
      "How-Tux","HP Secure OS Software for Linux","Hybryde Linux","Hymera","iBox","Icepack Linux","Ichthux",
      "IDMS Linux","Igelle DSV","Ignalum Linux","iMagic OS","Imagineos","Immunix Secure Server OS","Impi Linux",
      "IndLinux","Inquisitor","INSERT - Inside Security Rescue Toolkit","Insigne Linux","IPCop Firewall","iQunix OS","JackLab Audio Distribution",
      "JAMD Linux","JBLinux","Jibbed","JoLinux","Joli OS","Jollix","Julex",
      "JUSIX","K12Linux","Kaella, Knoppix Linux Azur","KahelOS","Kalango Linux","Karamad Linux","KateOS",
      "kademar Linux","Keysoft Linux","GNU/Linux Kinneret","Kiwi Linux","Klax Live-CD","Klikit-Linux","KlusTriX",
      "kmLinux","knopILS","Knoppel","Knopperdisk","Knoppix 64","KnoppiXMAME","KnoSciences",
      "Komodo Linux","Kondara MNU/Linux","Kongoni GNU/Linux","KoreLinux","Korora Project","KRUD","Kuki Linux",
      "Kurumin Linux","Kwheezy","KXStudio","LAMPPIX","LASER5 Linux","Local Area Security Linux (L.A.S.)","Leeenux",
      "Legacy OS","LG3D LiveCD","LGIS GNU/Linux","Liberté Linux","Libranet GNU/Linux","LIIS Linux","Linare Linux",
      "Lineox Enterprise Linux","LinEspa","LinEx","Linguas OS","LinnexOS","Linpus Linux","LinuxBBQ",
      "Linux-EduCD","linuX-gamers Live DVD","Linuxin GNU/Linux","LinuxInstall.org Project","LINUXO Live!","Linux+ Live","LinuxPPC",
      "LinuxTLE","Linux XP","Linvo GNU/Linux","Liquid Lemur Linux","Litrix Linux","Linux LiveCD Router","LiVux",
      "Linux Live Game Project","Linux Bootable Business Card (LNX-BBC)","Linux Loco","Lonix","LormaLinux","LRs GNU Linux","Luinux",
      "Luit Linux","Luminux","Lycoris Desktop/LX","Macpup","Madbox Linux","Madeinlinux","Magic Linux",
      "Mandows","Mandriva Linux","Linux Mangaka","Maryan Linux","Masonux","Matriux","Maui Linux",
      "MAX: Madrid_Linux","Mayix XliveCD","MCNLive","Linux Media Lab Distribution","MeeGo","MEPIS Linux","Merdeka Trustix Linux",
      "Metamorphose Linux","MIKO GNYO/Linux","MilaX","MINIX","Miracle Linux","Asianux","MirOS BSD",
      "MIZI Linux","Moblin","Mockup","MoLinux","Momonga Linux","Monomaxos","Monoppix",
      "m0n0wall","moonOS","Morphix","MoviX, MoviX², eMoviX","MSC.Linux","MUMi-LinuX","Munjoy Linux",
      "Muriqui Linux","Murix Linux","Musix GNU+Linux","Mutagenix","Myah OS","myLinux","Myrinix",
      "Mythbuntu","MythDora","Nanolinux","Nasgaïa GNU/Linux","Nature's Linux","Navyn OS","Neat-GNU/Linux",
      "NeoShine Linux","NepaLinux","Linux Netwosix","Nexenta OS","Niigata Linux","NimbleX","Nitix Autonomic Linux",
      "N-iX Desktop Linux","Nonux","NordisKnoppix","Nova","nUbuntu","NuxOne Linux","OEone HomeBase",
      "OpenGroupware.org Knoppix CD","Ojuba","OliveBSD","Olive","Onebase Linux","O-Net","Co-CreateLinux",
      "OpenELEC","Openfiler","OpenGEU","OpenLab GNU/Linux","OpenLX","OpenNA Linux","OpenSolaris",
      "Ophcrack LiveCD","Oralux","Otakux","Overclockix","OzOs","Oz Unity","PAIPIX",
      "PapugLinux","Parsix GNU/Linux","Parslinux GNU/Linux","Peachtree Linux","Pear Linux","PelicanHPC GNU Linux","Penguin Sleuth Bootable CD",
      "Metadistro-Pequelin","Phaeronix","Phayoune Secure Linux","PHLAK","Phinx Desktop","PHP Solutions Live CD","PiBang Linux",
      "Pidora","Pie Box Enterprise Linux","PilotLinux","Pingo Linux","Pingwinek GNU/Linux","Pioneer Linux","Plan-B",
      "Point Linux","Polar Bear Linux","PoliArch","Poseidon Linux","pQui Linux","Privatix Live-System","Progeny Debian",
      "Progex","Project development Enlightenment verbose (Project dEv)","Protech","Puredyne","QiLinux","Qimo 4 Kids","Qomo Linux",
      "Quantian Scientific Computing Environment","Quirky","Rails Live CD","RaspBSD","RasPlex","Rebellin Linux","RebornOS",
      "Red Flag Linux","Red Office Linux","redWall Firewall","Remix OS","REMnux","Resala Linux","Resulinux",
      "Revenge OS","RIPLinuX","ROCK Linux","Rocky Linux","Rockstor","RoFreeSBIE","ROOT GNU/Linux",
      "ROSLIMS Live CD","rPath Linux","Linux4all LiveCd","Rubix Linux","RUNT Linux","Sabily","SalentOS",
      "SalineOS","Salix","Saluki Linux","Salvare","SAMity Linux","Santa Fe Linux","Satux",
      "SaxenOS","SchilliX","Scientific Linux","Southern California Internet Linux","SCO Linux","Semplice Linux","SENTINIX",
      "Sentry Firewall CD","Shabdix GNU/Linux","SharkOS","Shift Linux","siduction","Slackintosh","Slamd64 Linux",
      "SLAMPP Live","Slavix","Slix","Slo-Tech Linux","SLYNUX","SmartPeer","Superb Mini Server",
      "SNAPPIX","Snøfrix","Snowlinux","Server Optimized Linux","SolusOS","Sonar GNU/Linux","Sorcerer",
      "LBA-Linux","Soyombo Mongolian Linux","Probatus Spectra Linux","SphinxOS","SprezzOS","SquiggleOS","Stampede Linux",
      "StartCom Linux","StartOS","STD - Security Tools Distribution","Storm Linux","StressLinux","STUX GNU/Linux","Subgraph OS",
      "SuliX","Sun Java Desktop System","RAYS","Super OS","SuperRescue CD","Suriyan","SwagArch GNU/Linux",
      "Swecha","Syllable Server","SymphonyOS","TA-Linux","Tablix on Morphix","TalkingArch","Tanglu",
      "Tango Studio","Tao Linux","Taprobane GNU/Linux","Tech Linux","TFM Linux","TPM - ThePacketMaster Linux Security Server",
      "Thisk Server","Thiz Linux","Tilix Linux","TinyMe","tinysofa classic / enterprise server","Toorox","Topologilinux",
      "ToriOS","Toutou Linux","TrianceOS","Trinity Rescue Kit","trixbox","Troppix","TrueBSD",
      "TrueOS","Trustix Secure Linux","Truva Linux","TrX Live Firewall","Tugux GNU/Linux","TumiX GNU/Linux","TupiServer Linux",
      "Tuquito","Turbolinux","Turkix","UberStudent","Ubuntu Christian Edition","Ubuntu GNOME","Ubuntu Rescue Remix",
      "UHU-Linux","U-lite","Ulteo Open Virtual Desktop","Ultima Linux","Ultramarine Linux","Underground Desktop","United Linux",
      "Unity Linux","uOS - The Micro Operating System","URIX OS","Userful Desktop","UserLinux","UTUTO","VAST (VIPER Assessment Security Tools)",
      "VectorLinux","VenenuX","VideoLinux","Vinux","Virtual-Linux","ViruX Linux Live CD","VLOS",
      "VMKnoppix","VNLinux","Voltalinux","Voodoo Linux","VortexBox","Vyatta","wattOS",
      "Wazobia Linux","White Box Enterprise Linux","WHAX","WIENUX","WinBi","Window Maker Live","Wolvix GNU/Linux",
      "WOMP!","WOW Linux","Xandros Desktop OS","Xarnoppix","X-Evian","Xfld","X/OS Linux",
      "xPUD","XStreamOS","Xteam Linux","Yellow Dog Linux","Yoper Linux","YES Linux","Zencafe GNU/Linux",
      "ZENIX GNU/Linux","Zen Linux","ZerahStar Zesktop","Zeus Linux","ZevenOS","ZoneCD","Zopix",
    ];
    return interaction
      .create({
        id: msg.id,
        token: msg.token,
        type: 'channelMessage',
        data: { content: `I am using ${distroSel[~~(Math.random() * distroSel.length)]} btw. 🔥👈😂` } 
      })
        .catch((err) => console.log(err));
  },
};
